spring:
  application:
    name: pedidos-ms
  rabbitmq:
    host: localhost
    port: 5672
    username: saviom
    password: alura
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
server:
  port: 0