management:
  endpoints:
    web:
      exposure:
        include: health,info
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        cors-configuration:
          '[/**]':
            allowed-origins: http://*
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true